import './globals.css'
import { Inter } from 'next/font/google'
import { MyContext} from "@/Context/Context";




const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shopping-List',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <MyContext>
          {children}
        </MyContext>

      </body>
    </html>
  )
}
